### ISSUE TITLE
RSS爬虫问题

### ISSUE THREAD

**Issue by coderZoe** [lyc8503/PTHackPoC#1]
首先感谢作者的代码和博客文章，写的很好。
提一些小的问题和疑惑：

首先 https://github.com/lyc8503/PTHackPoC/blob/master/py/crawl.py 这个脚本的passkey暴露了。

其次，我发现这个脚本请求几个主要的参数：
`?rows={size}&startindex={start}&icat=1&ismalldescr=1&isize=1&iuplder=1`
这里的`rows`、`startindex`、`icat`等参数不知道作者是从哪里获取的，因为我现在也需要从某些站点上爬取它的所有种子，但不知道我的站点是否也有这些参数，或者有没有其他入参

**Comment by lyc8503** [comment]
~~抱歉之前看到邮件提醒顺手点掉然后忘回了~~

> 这个脚本的passkey暴露了

感谢提醒

> 这里的rows、startindex、icat等参数不知道作者是从哪里获取的

这几个 RSS 的参数是阅读 `nexusphp` 的源代码得到的，RSS 本身没有规定标准的分页参数，但很多 PT 站点都使用了这份开源代码。（所以很多功能也一样）

参考：https://github.com/xiaomlove/nexusphp/blob/24936277dbed596991af4c3e4be0c1287d6abd4b/public/torrentrss.php#L79

**Comment by coderZoe** [comment]
> ~抱歉之前看到邮件提醒顺手点掉然后忘回了~
> 
> > 这个脚本的passkey暴露了
> 
> 感谢提醒
> 
> > 这里的rows、startindex、icat等参数不知道作者是从哪里获取的
> 
> 这几个 RSS 的参数是阅读 `nexusphp` 的源代码得到的，RSS 本身没有规定标准的分页参数，但很多 PT 站点都使用了这份开源代码。（所以很多功能也一样）
> 
> 参考：https://github.com/xiaomlove/nexusphp/blob/24936277dbed596991af4c3e4be0c1287d6abd4b/public/torrentrss.php#L79

感谢回复，我研究研究
